### PR TITLE
Add my files bro i am hungry and i feel so lightheaded

### PR DESCRIPTION
**Pull request by quin1sue**
LET ME EAT TONIGHT!!! I DESERVE A JOLLIBEE YUMBURGER AND THREE SPAGHETTIS!!!

### CODE REVIEW

**Comment by waffensultan** [comment]
Kasama sa PR mo yung .env file mo

Get ready to be hacked lil bro

**Comment by quin1sue** [comment]
> Kasama sa PR mo yung .env file mo
> 
> Get ready to be hacked lil bro

GET WRECKED I ALREADY REMOVED IT FOR CHRIST'S SAKE!!

**Comment by waffensultan** [comment]
## Bugs (Found in Testing):

1. The images disappear when you continuously change themes


This should be pretty self-explanatory: image

**Comment by quin1sue** [comment]
+1 unfinished project

**Comment by waffensultan** [comment]
> +1 unfinished project

Chat is this a W or an L?

**Comment by quin1sue** [comment]
WL

**Pull request closed without merging**
